// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PotterTravel.Data;

#nullable disable

namespace PotterTravel.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107002701_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PotterTravel.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClienteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteUrl = "localhost8081",
                            Cpf = "123457",
                            Email = "joao@gmail.com",
                            Nome = "Joao",
                            Senha = "444444",
                            Telefone = "36958746"
                        },
                        new
                        {
                            Id = 2,
                            ClienteUrl = "localhost8080",
                            Cpf = "123456",
                            Email = "maria@gmail.com",
                            Nome = "Maria",
                            Senha = "333333",
                            Telefone = "36958745"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
